<?php
function iq_lang_switcher_language_switch_links_alter(array &$links, $type, $path)
{
    if (\Drupal::currentUser()->hasPermission('bypass node access')) {
        return;
    }
    if ($node = \Drupal::routeMatch()->getParameter('node')) {
        $translations = $node->getTranslationLanguages(true); 
        foreach ($links as $langcode => $link) {
            if ($node) {
                if (array_key_exists($langcode, $translations)) {
                    $translation = $node->getTranslation($langcode);
                    if (!$translation->isPublished()) {
                        unset($links[$langcode]);
                    }
                } else {
                    unset($links[$langcode]);
                }
            }
        }
    }
}
